server:
  port: 8104
spring:
  # 数据库配置
  # todo 需替换配置
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yubi
    username: root
    password: root
  # Redis 配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
  devtools:
    livereload:
      port: 35731